### ISSUE TITLE
Viewer freezes as soon as connection is made

### ISSUE THREAD

**Issue by spens** [team696-public/dash696#1]
My pi is up and running.  I can view the video stream in a browser on port 8080.  I can see blob_count:0 and client_msec times scrolling like crazy with the Request_Time.java program.  I think everything is good on the pi end.

On the viewer side, I'm stuck.  I don't know python well and my searches to try and troubleshoot are not coming up with helpful results (like why can't I see the output from the print statements on my console - everything I find says use "from Tkinter ..." but when I modify "import Tkinter" to some version of "from Tkinter", the program won't even run.

Anyway, here is what I see.  I start the java program in eclipse it it displays messages that it cannot connect.  I launch "python dash696.py" on my command line and the Tk window launches.  It shows messages about not being able to connect.  I start the stream on the pi, and java starts showing blob counts (0 of course) and the Tk window shows I've connected.  Then the Tk window immediately freezes right there.  No other GUI elements are drawn, the GUI window is frozen and windows reports it as unresponsive.  The X to close the window doesn't work.  CTRL-C in the command window doesn't work.  If I stop the stream on the pi, the viewer does exit.

My guess is it is stuck in some event waiting for something, but I don't know what event or what it is waiting for.  At one point I killed the GUI window and got an exception on the console about a constant not being defined.  Maybe I need an older version of cv2?

I'm using Windows 10 with Python 2.7.15 from [here](https://www.python.org/downloads/release/python-2715/)
I ran "pip install Image" and "pip install opency-python" to resolve errors regarding missing Image and cv2 references.
The versions of these are:
```
python -c "import PIL.Image; print(PIL.Image.__version__)"
5.2.0
python -c "import cv2; print(cv2.__version__)"
3.4.2
```

This is what I see when it gets stuck:
![image1](https://user-images.githubusercontent.com/1720225/44625182-cbbeba00-a8c8-11e8-850b-f624a1ee6755.png)

![image2](https://user-images.githubusercontent.com/1720225/44625183-d5482200-a8c8-11e8-83d0-2041d852e258.png)

![image3](https://user-images.githubusercontent.com/1720225/44625185-d9743f80-a8c8-11e8-9706-9fe24e6799ef.png)

![image4](https://user-images.githubusercontent.com/1720225/44625186-dc6f3000-a8c8-11e8-98ad-9794120e67ca.png)

If anyone has suggestions or tips on what to try from here, I'd really appreciate it.

Thanks!
Bill

**Comment by spens** [comment]
I was able to work around this issue by rolling back the team696-public/mjpg-streamer to the Dec 2, 2017 check-in.

I'm not sure if I'm reading the code right, but the last check-in on the mjpg-streamer introduced a wait for client data:
`int bytes = recv(conn_args_ptr->client.fd, &msg, sizeof(Tcp_Params), 0);`

However, when I force stop the client, I see it is waiting for data from the mjpg-streamer:
`data = self.sock.recv(520)`

If they are both waiting on each other, that would explain the hanging behavior.


Additionally, I uninstalled the opencv version 3 with the command:
`pip uninstall opencv-python`

I reinstalled opencv version 2 by downloading the latest version 2 from here: [https://opencv.org/releases.html](https://opencv.org/releases.html)  (eg. 2.4.13.6 Win pack)

After running the exe (which extracts the files), I copied the file from C:\Users\bill\Downloads\cv2\opencv\build\python\2.7\x86\cv2.pyd to C:\Python27\Lib\site-packages\cv2.pyd (I'm using the 32-bit version of python)

You can use this command to verify you now have version 2: 
`python -c "import cv2; print(cv2.__version__)"`

Alternatively, you can replace cv2.CV_LOAD_IMAGE_COLOR with cv2.IMREAD_COLOR in the code and use version 3 (the latest) of opencv-python.  I've only tried to get the GUI up and running, so I haven't tested all of the functionality.

Hope this helps anyone else trying to get this awesome blob-tracking example working.

Bill

**Comment by daniel-clouse** [comment]
I was able to reproduce this problem.

When you push the "save" button in the GUI, a file named dash_696_config.bin is created.  This file holds the current configuration state.  When dash_696 starts up, it checks for this file and updates its configuration state then sends it to the mjpg-streamer process on the pi so that they are in sync.  The problem occurs when that file is missing.  In that case, dash_696 is supposed to notify mjpg-streamer of this and mjpg-streamer is supposed to use its default state.  That message was broken, so the two processes got out of sync, causing each processes to wait for a message from the other -- voila, deadlock.

The fix is in the latest push.  Be sure you pick up the changes both in dash696 and in mjpg-streamer or else other bad things will happen.
