### ISSUE TITLE
dashrds (created from dash966.py) is crashing - any thoughts

### ISSUE THREAD

**Issue by SnoBotics981** [team696-public/dash696#2]
When I attempt to run start_rds I'm getting the error, at the end of this issue. I did modify the ip address in dashrds.py. The contents of start_rds looks like:

export LD_LIBRARY_PATH=.
./mjpg_streamer -o "output_http.so -w 192.168.1.16 -p 10867" -i "input_raspicam_
696.so -x 640 -y 480 -vwidth 320 -vheight 240 -fps 30 -quality 20 -ex auto -blob
yuv 100,255,0,100,0,50 -ISO 100 -awbgainR 1.0 -awbgainB 1.0 -againtol 0.1 -dgain
tol 0.1 -awb auto

The output from start_rds looks like:

MJPG Streamer Version.: 2.0
FPS 30, Camera 640 x 480, Video 320 x 240
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 100, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
 o: www-folder-path......: 192.168.1.16/
 o: HTTP TCP port........: 10867
 o: HTTP Listen Address..: (null)
 o: username:password....: disabled
 o: commands.............: enabled
start up at Fri Nov  9 19:55:41 2018; usecs= 1809064969
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
can't mmal_component_create(camera)

python dashrds.py 

Traceback (most recent call last):
  File "dashrds.py", line 1179, in <module>
    dash_696 = Dash_696(SERVER_IP_ADDR, TCP_PORT, queue, crosshairs_position, quitter.do_quit)
  File "dashrds.py", line 912, in __init__
    self.tcp_comms.recv_tcp_params()
  File "dashrds.py", line 200, in recv_tcp_params
    self.tcp_params.crosshairs_y = struct.unpack('!10i56x3i4x4diffi296x4?6B2x4f2i28x', data)
struct.error: unpack requires a string argument of length 520

**Comment by daniel-clouse** [comment]
There are two errors here.  I'm going to ignore the error message from python for the moment and concentrate on the error message from start_rds.  On a hunch, I unplugged the camera from the raspberry pi  camera port, and I was able to reproduce your error message exactly.  This code requires a raspberry pi camera attached to the pi camera port.  Check your camera connection.  When your start_rds application is running properly, it will not write out an error message and it will continue to run.  The only way you know it's running is that it doesn't return to the shell.  It doesn't put out much output except for error messages.

If you get around that problem and the python error still persists, let me know and I will revisit the second error.

**Comment by robSteele-JPL** [comment]
Hooked up a raspberry pi camera to the raspberry pi camera port and got the start_rds.sh script to work. It was outputting to my local ip address of 192.168.1.19 port 10867. I was able to connect to the device using a web browser. So I could confirm images  were being streamed.

From there I tried running 'dashrds.py' - which failed. I'll provide detailed logging tonight. But I at least wanted to record my progress so far.

The camera I'm using is providing a very dark image. I was wondering if you @daniel-clouse might have a recommendation for a camera for the camera port.

**Comment by daniel-clouse** [comment]
Rob,
  Be sure to pull the latest from both the dash696 and mstreamer repos.  I fixed a bug over the weekend that was causing the GUI to deadlock.
You don’t have any choice in terms of camera with this software, but you do have control of brightness settings in the gui.  Try ISO, brightness, etc.  Some of the settings are arcane.  Let me know if this continues to be a problem.

-- Dan

**Comment by robSteele-JPL** [comment]
I did pull the latest version of the software.

Rob
818 395 4657 (cell)
Sent from my iPhone, mistypings may be observed.


On Nov 12, 2018, at 8:46 AM, Daniel Clouse <notifications@github.com<mailto:notifications@github.com>> wrote:

Rob,
Be sure to pull the latest from both the dash696 and mstreamer repos. I fixed a bug over the weekend that was causing the GUI to deadlock.
You don’t have any choice in terms of camera with this software, but you do have control of brightness settings in the gui. Try ISO, brightness, etc. Some of the settings are arcane. Let me know if this continues to be a problem.

-- Dan

**Comment by robSteele-JPL** [comment]
The parameters to .mjpg_streamer:

./mjpg_streamer -o "output_http.so -w 192.168.1.19 -p 10867" -i "input_raspicam_
696.so -x 640 -y 480 -vwidth 320 -vheight 240 -fps 30 -quality 20 -ex auto -blob
yuv 100,255,0,100,0,50 -ISO 100 -awbgainR 1.0 -awbgainB 1.0 -againtol 0.1 -dgain
tol 0.1 -awb auto -vf"

The output from starting:

/start_rds.sh
MJPG Streamer Version.: 2.0
FPS 30, Camera 640 x 480, Video 320 x 240
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 100, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip Yes
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
 o: www-folder-path......: 192.168.1.19/
 o: HTTP TCP port........: 10867
 o: HTTP Listen Address..: (null)
 o: username:password....: disabled
 o: commands.............: enabled
start up at Mon Nov 12 15:16:07 2018; usecs= 1878185085

The dump from dashrds.py after it connects. This has only been modified from
dash696.py by modifying the IP address and  the port numbers.

python dashrds.py
Traceback (most recent call last):
  File "dashrds.py", line 1181, in <module>
    dash_696 = Dash_696(SERVER_IP_ADDR, TCP_PORT, queue, crosshairs_position, qu
itter.do_quit)
  File "dashrds.py", line 914, in __init__
    self.tcp_comms.recv_tcp_params()
  File "dashrds.py", line 202, in recv_tcp_params
    self.tcp_params.crosshairs_y = struct.unpack('!10i56x3i4x4diffi296x4?6B2x4f2
i28x', data)
struct.error: unpack requires a string argument of length 520

**Comment by robSteele-JPL** [comment]
The original start_696.sh has the following for the output:
-o "output_http.so -w ./www"
When I tried using that in my start_rds.sh I got:
 o: www-folder-path......: ./www/
 o: HTTP TCP port........: 8080
 o: HTTP Listen Address..: (null)
 o: username:password....: disabled
 o: commands.............: enabled
bind: Address already in use
bind: Address already in use
 o: server_thread(): bind(8080) failed

I'm wondering if using the following: -o "output_http.so -w 192.168.1.16 -p 10867"

Was this correct or is there something I need to do to get the ./www to work

If this is documented I apologize - as I might have missed this in my reading.

**Comment by daniel-clouse** [comment]
I would not mess with the -o or -w option.  That's handled in part of mjpeg-streamer that I know nothing about.
If you want to change the ip address of the pi, you change SERVER_IP_ADDR around line 1172 in dash696.py.  Mjpeg-streamer figures out the ip address of the laptop automagically, so there is no place to change its address.

In fact, I don't see any reason why you would need to change anything in start_696.sh. 
Change SERVER_IP_ADDR as needed, but don't mess with port numbers as those need to be changed in multiple places.

You may need to reboot your pi to get around the "Address already in use" issues.

**Comment by robSteele-JPL** [comment]
So I went back and modified dash696.py to use the server ip address of 192.168.1.99 and am running start_696.sh without any modifications.

I tried rebooting and I'm still getting the 'address already in use' message. Any thoughts as to what I might try next?

Here is the output from the shell script:

./start_696.sh 
MJPG Streamer Version.: 2.0
FPS 30, Camera 640 x 480, Video 320 x 240
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 100, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
 o: www-folder-path......: ./www/
 o: HTTP TCP port........: 8080
 o: HTTP Listen Address..: (null)
 o: username:password....: disabled
 o: commands.............: enabled
start up at Wed Nov 14 20:57:47 2018; usecs= 472345924
bind: Address already in use
bind: Address already in use
 o: server_thread(): bind(8080) failed
pi@raspberrypi:~/git/team-696/mjpg-streamer/mjpg-streamer-experimental

**Comment by daniel-clouse** [comment]
??? Make sure no other programs are running.  Run the netstat command to get info about what ports are in use.

**Comment by robSteele-JPL** [comment]
Managed to figure out which process was interfering with my running the program by using:

sudo apt install lsof
sudo lsof -i tcp:8080
sudo lsof -i udp:8080

Killed the task and things are now starting to work for  me. So I'll close this issue and move on to actually running the program.

Thanks Dan for help with this.
